[book]
authors = ["Nami R."]
language = "en"
multilingual = false
src = "src"
title = "Cairo-to-Dojo Starter"
description = "A cairo-to-dojo starter reference guide for Cairo developers."

[theme]
[output.html]
additional-js = ["theme.js"]
additional-css = ["theme.css"]
